// Catálogo de ordenadores del Kit Digital. Fuente: kitdigital.ecomputer.es
// (modelos disponibles, fotos, precios y fichas técnicas). El Bono del Kit
// Digital cubre 1.000€; el cliente abona la diferencia ("pagas").

export type DeviceKind = "laptop" | "desktop";

export interface DeviceSpec {
  label: string;
  value: string;
}

export interface KitDevice {
  slug: string;
  brand: string;
  name: string;
  kind: DeviceKind;
  apple: boolean;
  blurb: string;
  description: string;
  highlights: string[];
  image: string;
  /** Precio total del equipo. */
  priceTotal: number;
  /** Lo que paga el cliente tras aplicar el bono (1.000€). */
  pricePay: number;
  /** Ficha técnica. */
  specs: DeviceSpec[];
}

/** Equipos Windows / PC, ordenados por precio. */
export const WINDOWS_DEVICES: KitDevice[] = [
  {
    slug: "lenovo-thinkbook-14-gen-8",
    brand: "Lenovo",
    name: "ThinkBook 14 Gen 8 - 14″ Core Ultra 5",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core Ultra 5 · 16GB · 512GB",
    description: "El Lenovo ThinkBook 14 Gen 8 - 14″ Core Ultra 5 equipa Intel Core Ultra 5, 16GB y 512GB con pantalla de 14″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["Intel Core Ultra 5", "16GB · 512GB", "14″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkbook-14-gen-8.webp",
    priceTotal: 1149,
    pricePay: 149,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "14\"" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "lenovo-thinkbook-14-gen-9-amd",
    brand: "Lenovo",
    name: "ThinkBook 14 Gen 9 AMD - 14″",
    kind: "laptop",
    apple: false,
    blurb: "AMD Ryzen · 16GB · 512GB",
    description: "El Lenovo ThinkBook 14 Gen 9 AMD - 14″ equipa AMD Ryzen, 16GB y 512GB con pantalla de 14″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["AMD Ryzen", "16GB · 512GB", "14″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkbook-14-gen-9-amd.webp",
    priceTotal: 1149,
    pricePay: 149,
    specs: [
      { label: "Procesador", value: "AMD Ryzen" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "14\"" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "lenovo-thinkbook-16-gen-9-amd",
    brand: "Lenovo",
    name: "ThinkBook 16 Gen 9 AMD - 16″",
    kind: "laptop",
    apple: false,
    blurb: "AMD Ryzen · 16GB · 512GB",
    description: "El Lenovo ThinkBook 16 Gen 9 AMD - 16″ equipa AMD Ryzen, 16GB y 512GB con pantalla de 16″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["AMD Ryzen", "16GB · 512GB", "16″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkbook-16-gen-9-amd.webp",
    priceTotal: 1149,
    pricePay: 149,
    specs: [
      { label: "Procesador", value: "AMD Ryzen" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "16\"" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "lenovo-thinkbook-16-gen-9-intel",
    brand: "Lenovo",
    name: "ThinkBook 16 Gen 9 Intel - 16″",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core i5 · 16GB · 512GB",
    description: "El Lenovo ThinkBook 16 Gen 9 Intel - 16″ equipa Intel Core i5, 16GB y 512GB con pantalla de 16″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["Intel Core i5", "16GB · 512GB", "16″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkbook-16-gen-9-intel.webp",
    priceTotal: 1149,
    pricePay: 149,
    specs: [
      { label: "Procesador", value: "Intel Core i5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "16\"" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "acer-travelmate-p2-16",
    brand: "Acer",
    name: "TravelMate P2-16″",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core i5 · 16GB · 512GB",
    description: "El Acer TravelMate P2-16″ equipa Intel Core i5, 16GB y 512GB con pantalla de 16″. Equilibrio entre rendimiento y precio con certificación profesional.",
    highlights: ["Intel Core i5", "16GB · 512GB", "16″ de pantalla"],
    image: "/img/kit-digital/acer-travelmate-p2-16.webp",
    priceTotal: 1159,
    pricePay: 159,
    specs: [
      { label: "Procesador", value: "Intel Core i5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "16\" (1920 x 1200)" },
      { label: "Marca", value: "Acer" },
    ],
  },
  {
    slug: "asus-expertbook-b34-14",
    brand: "Asus",
    name: "ExpertBook B34 14″ CORE ULTRA 7",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core Ultra 7 · 16GB · 512GB",
    description: "El Asus ExpertBook B34 14″ CORE ULTRA 7 equipa Intel Core Ultra 7, 16GB y 512GB con pantalla de 14″. La durabilidad y seguridad de la gama ExpertBook de Asus.",
    highlights: ["Intel Core Ultra 7", "16GB · 512GB", "14″ de pantalla"],
    image: "/img/kit-digital/asus-expertbook-b34-14.webp",
    priceTotal: 1199,
    pricePay: 199,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 7" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "14\" (1920 x 1200)" },
      { label: "Marca", value: "Asus" },
    ],
  },
  {
    slug: "lenovo-thinkcentre-m75q-monitor",
    brand: "Lenovo",
    name: "ThinkCentre M75q G5 + Monitor 23,8″ + Teclado + Ratón",
    kind: "desktop",
    apple: false,
    blurb: "AMD Ryzen · 16GB · 512GB",
    description: "El Lenovo ThinkCentre M75q G5 + Monitor 23,8″ + Teclado + Ratón equipa AMD Ryzen, 16GB y 512GB. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["AMD Ryzen", "16GB · 512GB", "Soporte técnico incluido"],
    image: "/img/kit-digital/lenovo-thinkcentre-m75q-monitor.webp",
    priceTotal: 1249,
    pricePay: 249,
    specs: [
      { label: "Procesador", value: "AMD Ryzen" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "23,8\" (1920×1080)" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "dell-pro-micro",
    brand: "Dell",
    name: "PRO Micro QCM1250 Core Ultra 5+ Monitor Dell E2425HSM 23,8″",
    kind: "desktop",
    apple: false,
    blurb: "Intel Core Ultra 5 · 16GB · 512GB",
    description: "El Dell PRO Micro QCM1250 Core Ultra 5+ Monitor Dell E2425HSM 23,8″ equipa Intel Core Ultra 5, 16GB y 512GB. La robustez y el soporte profesional de Dell.",
    highlights: ["Intel Core Ultra 5", "16GB · 512GB", "Soporte técnico incluido"],
    image: "/img/kit-digital/dell-pro-micro.webp",
    priceTotal: 1299,
    pricePay: 299,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "23,8\" (1920×1080)" },
      { label: "Marca", value: "Dell" },
    ],
  },
  {
    slug: "lenovo-thinkcentre-m75q-monitor-tactil",
    brand: "Lenovo",
    name: "ThinkCentre M75q G5 + Monitor 23,8″ Táctil + Teclado + Ratón",
    kind: "desktop",
    apple: false,
    blurb: "AMD Ryzen · 16GB · 512GB",
    description: "El Lenovo ThinkCentre M75q G5 + Monitor 23,8″ Táctil + Teclado + Ratón equipa AMD Ryzen, 16GB y 512GB. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["AMD Ryzen", "16GB · 512GB", "Soporte técnico incluido"],
    image: "/img/kit-digital/lenovo-thinkcentre-m75q-monitor-tactil.webp",
    priceTotal: 1299,
    pricePay: 299,
    specs: [
      { label: "Procesador", value: "AMD Ryzen" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "23,8\" (1920×1080)" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "lenovo-thinkpad-e16-gen-3",
    brand: "Lenovo",
    name: "ThinkPad E16 Gen 3 - 16″ Core Ultra 7 32Gb 1Tb",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core Ultra 7 · 32GB · 1TB",
    description: "El Lenovo ThinkPad E16 Gen 3 - 16″ Core Ultra 7 32Gb 1Tb equipa Intel Core Ultra 7, 32GB y 1TB con pantalla de 16″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["Intel Core Ultra 7", "32GB · 1TB", "16″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkpad-e16-gen-3.webp",
    priceTotal: 1679,
    pricePay: 679,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 7" },
      { label: "RAM", value: "32GB RAM" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "16\" (1920 x 1200)" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "samsung-book5-pro-360",
    brand: "Samsung",
    name: "Book5 Pro 360 16″ Ultra7",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core Ultra 7 · 32GB · 1TB",
    description: "El Samsung Book5 Pro 360 16″ Ultra7 equipa Intel Core Ultra 7, 32GB y 1TB. Diseño premium y pantalla brillante de Samsung.",
    highlights: ["Intel Core Ultra 7", "32GB · 1TB", "Soporte técnico incluido"],
    image: "/img/kit-digital/samsung-book5-pro-360.webp",
    priceTotal: 1999,
    pricePay: 999,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 7" },
      { label: "RAM", value: "32GB RAM" },
      { label: "Disco", value: "1TB" },
      { label: "Marca", value: "Samsung" },
    ],
  },
  {
    slug: "lenovo-thinkpad-p14s-gen-6",
    brand: "Lenovo",
    name: "ThinkPad P14s Gen 6 14.5″",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core Ultra 7 · 32GB · 1TB",
    description: "El Lenovo ThinkPad P14s Gen 6 14.5″ equipa Intel Core Ultra 7, 32GB y 1TB con pantalla de 14,5″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["Intel Core Ultra 7", "32GB · 1TB", "14,5″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkpad-p14s-gen-6.webp",
    priceTotal: 2549,
    pricePay: 1549,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 7" },
      { label: "RAM", value: "32GB RAM" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "14,5\" (1920×1200)" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "lenovo-thinkpad-p16s-gen-4",
    brand: "Lenovo",
    name: "ThinkPad P16s Gen 4 (Intel)",
    kind: "laptop",
    apple: false,
    blurb: "Intel Core Ultra 7 · 32GB · 1TB",
    description: "El Lenovo ThinkPad P16s Gen 4 (Intel) equipa Intel Core Ultra 7, 32GB y 1TB con pantalla de 16″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["Intel Core Ultra 7", "32GB · 1TB", "16″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkpad-p16s-gen-4.webp",
    priceTotal: 2599,
    pricePay: 1599,
    specs: [
      { label: "Procesador", value: "Intel Core Ultra 7" },
      { label: "RAM", value: "32GB RAM" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "16\" (1920 x 1200)" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
  {
    slug: "lenovo-thinkbook-16p-gen-6",
    brand: "Lenovo",
    name: "ThinkBook 16p Gen 6 -16″",
    kind: "laptop",
    apple: false,
    blurb: "AMD Ryzen · 32GB · 1TB",
    description: "El Lenovo ThinkBook 16p Gen 6 -16″ equipa AMD Ryzen, 32GB y 1TB con pantalla de 16″. La fiabilidad y el teclado de referencia de Lenovo para empresa.",
    highlights: ["AMD Ryzen", "32GB · 1TB", "16″ de pantalla"],
    image: "/img/kit-digital/lenovo-thinkbook-16p-gen-6.webp",
    priceTotal: 2899,
    pricePay: 1899,
    specs: [
      { label: "Procesador", value: "AMD Ryzen" },
      { label: "RAM", value: "32GB RAM" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "16\" (2560×1600)" },
      { label: "Marca", value: "Lenovo" },
    ],
  },
];

/** Equipos Apple, ordenados por precio. */
export const APPLE_DEVICES: KitDevice[] = [
  {
    slug: "macbook-air-13-m5",
    brand: "Apple",
    name: "MacBook AIR 13″ M5",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 · 16GB · 512GB",
    description: "El Apple MacBook AIR 13″ M5 equipa Chip M5, 16GB y 512GB con pantalla de 13″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5", "16GB · 512GB", "13″ de pantalla"],
    image: "/img/kit-digital/macbook-air-13-m5.webp",
    priceTotal: 1399,
    pricePay: 399,
    specs: [
      { label: "Procesador", value: "Chip M5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "13\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Azul Cielo, Blanco estrella, Medianoche, Plata" },
    ],
  },
  {
    slug: "macbook-air-15-m5",
    brand: "Apple",
    name: "MacBook AIR 15″ M5",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 · 16GB · 512GB",
    description: "El Apple MacBook AIR 15″ M5 equipa Chip M5, 16GB y 512GB con pantalla de 15″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5", "16GB · 512GB", "15″ de pantalla"],
    image: "/img/kit-digital/macbook-air-15-m5.webp",
    priceTotal: 1599,
    pricePay: 599,
    specs: [
      { label: "Procesador", value: "Chip M5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "512GB" },
      { label: "Resolución", value: "15\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Azul Cielo, Blanco estrella, Medianoche, Plata" },
    ],
  },
  {
    slug: "macbook-pro-14-m5",
    brand: "Apple",
    name: "MacBook PRO 14″ M5 16Gb 1Tb",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 · 16GB · 1TB",
    description: "El Apple MacBook PRO 14″ M5 16Gb 1Tb equipa Chip M5, 16GB y 1TB con pantalla de 14″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5", "16GB · 1TB", "14″ de pantalla"],
    image: "/img/kit-digital/macbook-pro-14-m5.webp",
    priceTotal: 2049,
    pricePay: 1049,
    specs: [
      { label: "Procesador", value: "Chip M5" },
      { label: "RAM", value: "16GB RAM" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "14\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Negro Espacial, Plata" },
    ],
  },
  {
    slug: "macbook-pro-14-m5-24gb",
    brand: "Apple",
    name: "MacBook PRO 14″ M5 24Gb 1Tb",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 · 24GB · 1TB",
    description: "El Apple MacBook PRO 14″ M5 24Gb 1Tb equipa Chip M5, 24GB y 1TB con pantalla de 14″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5", "24GB · 1TB", "14″ de pantalla"],
    image: "/img/kit-digital/macbook-pro-14-m5-24gb.webp",
    priceTotal: 2249,
    pricePay: 1249,
    specs: [
      { label: "Procesador", value: "Chip M5" },
      { label: "RAM", value: "24GB" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "14\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Negro Espacial, Plata" },
    ],
  },
  {
    slug: "macbook-pro-14-m5-pro",
    brand: "Apple",
    name: "MacBook PRO 14″ M5 PRO 24GB 1TB",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 Pro · 24GB · 1TB",
    description: "El Apple MacBook PRO 14″ M5 PRO 24GB 1TB equipa Chip M5 Pro, 24GB y 1TB con pantalla de 14″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5 Pro", "24GB · 1TB", "14″ de pantalla"],
    image: "/img/kit-digital/macbook-pro-14-m5-pro.webp",
    priceTotal: 2499,
    pricePay: 1499,
    specs: [
      { label: "Procesador", value: "Chip M5 Pro" },
      { label: "RAM", value: "24GB" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "14\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Negro Espacial, Plata" },
    ],
  },
  {
    slug: "macbook-pro-16-m5-pro",
    brand: "Apple",
    name: "MacBook PRO 16″ M5 PRO 24GB 1TB",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 Pro · 24GB · 1TB",
    description: "El Apple MacBook PRO 16″ M5 PRO 24GB 1TB equipa Chip M5 Pro, 24GB y 1TB con pantalla de 16″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5 Pro", "24GB · 1TB", "16″ de pantalla"],
    image: "/img/kit-digital/macbook-pro-16-m5-pro.webp",
    priceTotal: 2949,
    pricePay: 1949,
    specs: [
      { label: "Procesador", value: "Chip M5 Pro" },
      { label: "RAM", value: "24GB" },
      { label: "Disco", value: "1TB" },
      { label: "Resolución", value: "16\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Negro Espacial, Plata" },
    ],
  },
  {
    slug: "macbook-pro-14-m5-max",
    brand: "Apple",
    name: "MacBook PRO 14″ M5 MAX 36GB 2TB",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 Max · 36GB · 2TB",
    description: "El Apple MacBook PRO 14″ M5 MAX 36GB 2TB equipa Chip M5 Max, 36GB y 2TB con pantalla de 14″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5 Max", "36GB · 2TB", "14″ de pantalla"],
    image: "/img/kit-digital/macbook-pro-14-m5-max.webp",
    priceTotal: 3899,
    pricePay: 2899,
    specs: [
      { label: "Procesador", value: "Chip M5 Max" },
      { label: "RAM", value: "36GB" },
      { label: "Disco", value: "2TB" },
      { label: "Resolución", value: "14\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Negro Espacial, Plata" },
    ],
  },
  {
    slug: "macbook-pro-16-m5-max",
    brand: "Apple",
    name: "MacBook PRO 16″ M5 MAX 36GB 2TB",
    kind: "laptop",
    apple: true,
    blurb: "Chip M5 Max · 36GB · 2TB",
    description: "El Apple MacBook PRO 16″ M5 MAX 36GB 2TB equipa Chip M5 Max, 36GB y 2TB con pantalla de 16″. Toda la potencia y autonomía del ecosistema Mac para tu día a día.",
    highlights: ["Chip M5 Max", "36GB · 2TB", "16″ de pantalla"],
    image: "/img/kit-digital/macbook-pro-16-m5-max.webp",
    priceTotal: 4199,
    pricePay: 3199,
    specs: [
      { label: "Procesador", value: "Chip M5 Max" },
      { label: "RAM", value: "36GB" },
      { label: "Disco", value: "2TB" },
      { label: "Resolución", value: "16\"" },
      { label: "Marca", value: "Apple" },
      { label: "Colores", value: "Negro Espacial, Plata" },
    ],
  },
];

export const ALL_DEVICES: KitDevice[] = [...WINDOWS_DEVICES, ...APPLE_DEVICES];

/** Precio "pagas" más bajo del catálogo (para el gancho de la landing). */
export const MIN_PAY = Math.min(...ALL_DEVICES.map((d) => d.pricePay));

export function deviceLabel(d: KitDevice): string {
  return `${d.brand} ${d.name}`;
}

export function getDevice(slug: string): KitDevice | undefined {
  return ALL_DEVICES.find((d) => d.slug === slug);
}

export const ALL_DEVICE_OPTIONS: string[] = ALL_DEVICES.map(deviceLabel);

export const KIT_TERMS: string[] = [
  "El dispositivo se entrega dentro de España.",
  "Servicio de soporte técnico incluido (avisos por email, atención de lunes a viernes de 09:00 a 17:00).",
  "Reparaciones en remoto o in situ por rotura, desperfectos o configuración, siempre con un uso correcto del equipo.",
  "Tiempo máximo de reparación de 5 días laborables o equipo de sustitución.",
  "Solo pueden beneficiarse quienes ya hayan validado otra solución de digitalización (art. 18.2 de las bases reguladoras).",
  "El Bono del Kit Digital cubre 1.000€ del valor del equipo; abonas únicamente la diferencia.",
];
