-- Alta de las dos secuencias de captación de la marca «dinkbit»: clínicas
-- dentales y consultas de psicología.
--
-- Ejecutar una vez en el SQL Editor de Supabase (proyecto wnboyesnlrbtwfmhcxmc),
-- después de docs/sql/2026-09-23-marca-dinkbit.sql (esa crea la marca).
--
-- El contenido sale de src/lib/ventas/secuencias-plantilla.ts, que es donde
-- está testeado. Si se edita la secuencia en el panel, manda el panel: este
-- fichero solo siembra el punto de partida y no vuelve a tocarlas (el
-- `not exists` por nombre evita duplicarlas si se ejecuta dos veces).
--
-- Quedan en estado «borrador». Activarlas es un clic en el panel, y conviene
-- hacerlo cuando estén revisadas.

insert into public.ventas_secuencias (marca_id, nombre, estado, pasos)
select m.id, 'Captación clínicas dentales', 'borrador', '{"version":1,"inicio":"inicio","pasos":{"inicio":{"tipo":"mensaje","texto":"Hola {{contacto}}, soy {{remitente}} de {{marca}}. Trabajamos con clínicas dentales en captación de pacientes.\n\nEn dental lo caro no suele ser llenar la agenda, sino llenarla de primeras visitas que no acaban en tratamiento. ¿Te cuento en dos minutos cómo lo medimos?","botones":[{"texto":"Sí, cuéntame","ruta":{"ir_a":"publicidad"}},{"texto":"Ahora no","ruta":{"ir_a":"ahora_no"}}]},"ahora_no":{"tipo":"mensaje","texto":"Sin problema, {{contacto}}. Te escribo en unos días por si entonces te viene mejor.","botones":[],"ruta":{"esperar_dias":7,"ir_a":"reintento"}},"reintento":{"tipo":"mensaje","texto":"Hola {{contacto}}, retomo aquello de la captación de pacientes para {{negocio}}. ¿Le echamos un vistazo ahora?","botones":[{"texto":"Va, cuéntame","ruta":{"ir_a":"publicidad"}},{"texto":"Mejor no","ruta":{"terminar":true}}]},"publicidad":{"tipo":"mensaje","texto":"Antes de nada, para no contarte lo que ya sabes: ¿inviertes ahora mismo en publicidad para traer pacientes?","botones":[{"texto":"Sí, cada mes","ruta":{"ir_a":"problemas"}},{"texto":"Todavía no","ruta":{"ir_a":"problemas"}},{"texto":"Lo probé y lo dejé","ruta":{"ir_a":"problemas"}}]},"problemas":{"tipo":"mensaje","texto":"¿Qué se parece más a lo que te pasa hoy en la clínica?","botones":[{"texto":"Faltan pacientes","ruta":{"ir_a":"cierre_faltan"}},{"texto":"Primera visita y ya","ruta":{"ir_a":"cierre_no_arrancan"}},{"texto":"Vienen y no vuelven","ruta":{"ir_a":"cierre_no_vuelven"}}],"guardar_respuesta_en":"problema_principal"},"cierre_faltan":{"tipo":"mensaje","texto":"Entendido. Ahí lo primero es saber cuánto te cuesta traer un paciente y cuánto te deja, porque sin eso invertir es apostar.\n\nTenemos una calculadora que lo hace con tus propios números en un minuto: dinkbit.es/escala/dental\n\nLe digo a mi compañera que te escriba para verlo contigo.","botones":[],"ruta":{"avisar":true,"fase":"interesado","terminar":true}},"cierre_no_arrancan":{"tipo":"mensaje","texto":"Ese es el bueno, y es el más caro: pagas por traer a alguien que se queda en la primera visita.\n\nPasa cuando una campaña se mide por citas. Nosotros la medimos por lo que factura cada paciente, así que a los dos meses sabes qué tratamiento te está pagando las campañas y cuál no. Suelen salir menos pacientes y más beneficio.\n\nLe digo a mi compañera que te escriba y te lo enseña con tus cifras.","botones":[],"ruta":{"avisar":true,"fase":"interesado","terminar":true}},"cierre_no_vuelven":{"tipo":"mensaje","texto":"Entonces el problema no está en la entrada, está en el seguimiento: cada paciente que no vuelve es beneficio que ya habías pagado por traer.\n\nEso se ve en el panel mes a mes, con su origen y su ficha, y se corrige. Le digo a mi compañera que te escriba y lo vemos con tu caso.","botones":[],"ruta":{"avisar":true,"fase":"interesado","terminar":true}}}}'::jsonb
from public.ventas_marcas m
where m.slug = 'dinkbit'
  and not exists (
    select 1 from public.ventas_secuencias s
    where s.marca_id = m.id and s.nombre = 'Captación clínicas dentales'
  );

insert into public.ventas_secuencias (marca_id, nombre, estado, pasos)
select m.id, 'Captación consultas de psicología', 'borrador', '{"version":1,"inicio":"inicio","pasos":{"inicio":{"tipo":"mensaje","texto":"Hola {{contacto}}, soy {{remitente}} de {{marca}}. Ayudamos a consultas de psicología a llenar los huecos de la agenda.\n\nSe puede ser muy buen profesional y tener la agenda a medias: son dos cosas distintas. ¿Te cuento en dos minutos cómo lo trabajamos?","botones":[{"texto":"Sí, cuéntame","ruta":{"ir_a":"publicidad"}},{"texto":"Ahora no","ruta":{"ir_a":"ahora_no"}}]},"ahora_no":{"tipo":"mensaje","texto":"Sin problema, {{contacto}}. Te escribo en unos días por si entonces te viene mejor.","botones":[],"ruta":{"esperar_dias":7,"ir_a":"reintento"}},"reintento":{"tipo":"mensaje","texto":"Hola {{contacto}}, retomo aquello de llenar la agenda de {{negocio}}. ¿Lo vemos ahora?","botones":[{"texto":"Va, cuéntame","ruta":{"ir_a":"publicidad"}},{"texto":"Mejor no","ruta":{"terminar":true}}]},"publicidad":{"tipo":"mensaje","texto":"Antes de nada, para no contarte lo que ya sabes: ¿inviertes ahora mismo en publicidad para traer pacientes?","botones":[{"texto":"Sí, cada mes","ruta":{"ir_a":"problemas"}},{"texto":"Todavía no","ruta":{"ir_a":"problemas"}},{"texto":"Lo probé y lo dejé","ruta":{"ir_a":"problemas"}}]},"problemas":{"tipo":"mensaje","texto":"¿Qué se parece más a lo que te pasa hoy en la consulta?","botones":[{"texto":"Huecos en la agenda","ruta":{"ir_a":"cierre_huecos"}},{"texto":"Vienen 1 vez y ya","ruta":{"ir_a":"cierre_abandono"}},{"texto":"Solo boca a boca","ruta":{"ir_a":"cierre_boca_a_boca"}}],"guardar_respuesta_en":"problema_principal"},"cierre_huecos":{"tipo":"mensaje","texto":"Es lo más habitual. Una consulta privada tiene unas 25 sesiones de hueco a la semana y con el boca a boca se queda en torno al 60 % de ocupación.\n\nTrabajamos justo eso: traer pacientes nuevos cada mes hasta llenar la agenda. Puedes ver cómo salen los números con los tuyos aquí: dinkbit.es/escala/psicologia\n\nLe digo a mi compañera que te escriba para verlo contigo.","botones":[],"ruta":{"avisar":true,"fase":"interesado","terminar":true}},"cierre_abandono":{"tipo":"mensaje","texto":"Eso cambia mucho la cuenta: si el paciente no sigue, cada hueco vuelve a abrirse al mes siguiente y hay que llenarlo otra vez.\n\nPor eso medimos no solo cuántos llegan, sino cuántos se quedan a seguir, y de qué campaña viene cada uno. Le digo a mi compañera que te escriba y lo vemos con tu agenda.","botones":[],"ruta":{"avisar":true,"fase":"interesado","terminar":true}},"cierre_boca_a_boca":{"tipo":"mensaje","texto":"El boca a boca es la mejor señal de que lo haces bien, pero no lo puedes abrir el día que tienes la agenda floja.\n\nLa idea es dejarlo donde está y sumarle un canal que sí puedas regular. Le digo a mi compañera que te escriba y te cuenta cómo se empieza sin liarse.","botones":[],"ruta":{"avisar":true,"fase":"interesado","terminar":true}}}}'::jsonb
from public.ventas_marcas m
where m.slug = 'dinkbit'
  and not exists (
    select 1 from public.ventas_secuencias s
    where s.marca_id = m.id and s.nombre = 'Captación consultas de psicología'
  );
